# Site
name: 'Ding Gang Chen'
description: '1'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/CDG'
disqus: 'demowebsite'
email: 'clint_chan@foxmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Clint_chan:
      name:           Clint_chan
      site:           https://clint-chan.github.io/CDG/
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Clint_chan, the author of this blog, the theme you're currently previewing. I hope you like it!"
      email:          cint_chan@foxmail.com
      QQ:             https://user.qzone.qq.com/945036663/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Clint_chan
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
